# Travis CI script
language: java

os:
- linux
- osx

sudo: false

services:
- docker

env:
  - BUILD_TYPE=default
  - BUILD_TYPE=android
  - BUILD_TYPE=cmake
  - BUILD_TYPE=check_zproto
  - BUILD_TYPE=check_zproject
  - BUILD_TYPE=bindings BINDING=jni

# osx environment does not have docker
matrix:
  exclude:
  - os: osx
    env: BUILD_TYPE=check_zproto
  - os: osx
    env: BUILD_TYPE=check_zproject
  - os: osx
    env: BUILD_TYPE=bindings BINDING=jni
  include:
  - env: BUILD_TYPE=valgrind
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev
        - valgrind

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils ; fi

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh

